# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtype',
            name='fa_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='fa_class',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
