# Generated by Django 2.2 on 2019-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20180905_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='station_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
