# Generated by Django 2.2 on 2019-08-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='omit_audit',
            field=models.BooleanField(null=True),
        ),
    ]
