# Generated by Django 2.2 on 2019-09-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0008_printqueue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printqueue',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='asset',
            name='decommissioned',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='decommissioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='decommissioned_reason',
            field=models.TextField(null=True),
        ),
    ]
