# Generated by Django 2.2 on 2019-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20190911_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
