# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipv4_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('mac_address', models.CharField(max_length=120, null=True)),
                ('network_type', models.CharField(choices=[('Wireless', 'Wireless'), ('Ethernet', 'Ethernet'), ('Alias', 'Alias'), ('Fiber', 'Fiber')], max_length=120, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4')),
                ('ipv4_netmask', models.GenericIPAddressField(protocol='IPv4')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assigned_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assets.Asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assetnetwork',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='networks.Network'),
        ),
    ]
