# Generated by Django 2.2 on 2019-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='available_licenses',
            field=models.IntegerField(null=True),
        ),
    ]
