# Generated by Django 2.2 on 2019-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20190509_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlicense',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
